application: async-chat
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# static link
- url: /fonts
  static_dir: fonts
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /js
  static_dir: js

libraries:
- name: webapp2
  version: "2.5.2"
